version: '3.9'
services:
  ho-webserver:
    build:
      context: ./.docker/server_http
      args:
        TIMEZONE: ${TIMEZONE}
    labels:
      ho.ctf.cyrhades: "1"
    ports:
      - ${PORT}:80
    environment:
      - HOOS_CTF_USERNAME=${HOOS_CTF_USERNAME:-}
    restart: always
    volumes:
      - web:/var/www/html
    read_only: true
    tmpfs:
      - /var/run/apache2/
      - /tmp
      - /var/tmp
      - /var/log/apache2
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    labels:
      ho.ctf.cyrhades: "1"
    environment:
      MYSQL_ROOT_PASSWORD: superSqlPassw0rD
      MYSQL_DATABASE: boutik
      MYSQL_USER: boutik_user
      MYSQL_PASSWORD: simpleSqlPass
    volumes:
      - ./.docker/db/init.sql:/docker-entrypoint-initdb.d
  composer:
    image: composer
    labels:
      ho.ctf.cyrhades: "1"
    volumes:
      - web:/app
    command: composer install --ignore-platform-reqs
volumes:
  web:
    name: web
    labels:
      ho.ctf.cyrhades: "1"
